package models

// DocumentStatus enumerates documented lifecycle states and compatible states
// returned by current or earlier Assinafy deployments.
type DocumentStatus string

// Documented and compatibility values for DocumentStatus.
const (
	// StatusUploading means the source upload is in progress.
	StatusUploading DocumentStatus = "uploading"
	// StatusUploaded means the source was accepted but metadata is not yet ready.
	StatusUploaded DocumentStatus = "uploaded"
	// StatusMetadataProcessing means page metadata is being generated.
	StatusMetadataProcessing DocumentStatus = "metadata_processing"
	// StatusMetadataReady means page metadata is available.
	StatusMetadataReady DocumentStatus = "metadata_ready"
	// StatusExpired means the signing deadline passed.
	StatusExpired DocumentStatus = "expired"
	// StatusCertificating means the signed artifact is being certified.
	StatusCertificating DocumentStatus = "certificating"
	// StatusCertificated means certification completed.
	StatusCertificated DocumentStatus = "certificated"
	// StatusRejectedBySigner means a signer declined the document.
	StatusRejectedBySigner DocumentStatus = "rejected_by_signer"
	// StatusPendingSignature means one signature is pending.
	StatusPendingSignature DocumentStatus = "pending_signature"
	// StatusPendingSignatures is a compatibility state for multiple pending signatures.
	StatusPendingSignatures DocumentStatus = "pending_signatures"
	// StatusPartiallySigned is a compatibility state for partial completion.
	StatusPartiallySigned DocumentStatus = "partially_signed"
	// StatusReady is a compatibility state indicating readiness for the next operation.
	StatusReady DocumentStatus = "ready"
	// StatusRejectedByUser means the document owner rejected or cancelled it.
	StatusRejectedByUser DocumentStatus = "rejected_by_user"
	// StatusFailed means document processing failed.
	StatusFailed DocumentStatus = "failed"
)

// Document is the canonical document object returned by document endpoints.
type Document struct {
	// Resource is the API resource discriminator when present.
	Resource string `json:"resource,omitempty"`
	// ID is the document identifier.
	ID string `json:"id"`
	// AccountID is the owning account identifier.
	AccountID string `json:"account_id"`
	// TemplateID is the nullable source-template identifier.
	TemplateID *string `json:"template_id,omitempty"`
	// Name is the document display name.
	Name string `json:"name"`
	// Status is the current lifecycle code.
	Status DocumentStatus `json:"status"`
	// Artifacts contains nullable download URLs when generated by the endpoint.
	Artifacts *DocumentArtifacts `json:"artifacts,omitempty"`
	// IsClosed reports whether the signing process can no longer change.
	IsClosed bool `json:"is_closed"`
	// SigningURL is the nullable signer-facing URL returned in signing contexts.
	SigningURL *string `json:"signing_url,omitempty"`
	// DeclineReason is the nullable reason supplied when a signer declined.
	DeclineReason *string `json:"decline_reason,omitempty"`
	// DeclinedBy is the nullable signer that declined the document.
	DeclinedBy *Signer `json:"declined_by,omitempty"`
	// Tags lists labels attached to the document when included.
	Tags []Tag `json:"tags,omitempty"`
	// CreatedAt is the document creation date-time.
	CreatedAt Timestamp `json:"created_at"`
	// UpdatedAt is the document last-update date-time.
	UpdatedAt Timestamp `json:"updated_at"`
	// Assignment is the active signing assignment when included.
	Assignment *Assignment `json:"assignment,omitempty"`
	// Pages contains rendered page metadata when included.
	Pages []DocumentPage `json:"pages,omitempty"`
	// Activities contains audit-trail entries when included.
	Activities []DocumentActivity `json:"activities,omitempty"`
	// CurrentSigner identifies the active signer in signer-facing responses.
	CurrentSigner *Signer `json:"current_signer,omitempty"`
	// DownloadURL is a nullable URL for the available document artifact.
	DownloadURL *string `json:"download_url,omitempty"`
	// DownloadFinalURL is a nullable URL for the completed document artifact.
	DownloadFinalURL *string `json:"download_final_url,omitempty"`
}

// DocumentArtifacts lists the URLs exposed by the API for download endpoints.
type DocumentArtifacts struct {
	// Original is the nullable URL of the uploaded source artifact.
	Original *string `json:"original,omitempty"`
	// Certificated is the nullable URL of the certified artifact.
	Certificated *string `json:"certificated,omitempty"`
	// CertificatePage is the nullable URL of the certificate-page artifact.
	CertificatePage *string `json:"certificate-page,omitempty"`
	// PAdES is the nullable URL of the PAdES-signed PDF artifact.
	PAdES *string `json:"pades,omitempty"`
	// Bundle is the nullable URL of the downloadable artifact bundle.
	Bundle *string `json:"bundle,omitempty"`
	// Thumbnail is the nullable URL of the generated thumbnail.
	Thumbnail *string `json:"thumbnail,omitempty"`
}

// DocumentPage describes a single page rendered from the source PDF.
type DocumentPage struct {
	// ID is the page identifier used by field-placement and page-download endpoints.
	ID string `json:"id"`
	// Number is the one-based page number.
	Number int `json:"number"`
	// Height is the rendered page height in the API's 150-DPI coordinate system.
	Height int `json:"height"`
	// Width is the rendered page width in the API's 150-DPI coordinate system.
	Width int `json:"width"`
	// DownloadURL is the absolute URL returned for the rendered page.
	DownloadURL string `json:"download_url"`
}

// DocumentActivity represents a single audit-trail entry on a document.
type DocumentActivity struct {
	// ID is the numeric audit event identifier.
	ID int `json:"id"`
	// Event is the machine-readable activity code.
	Event string `json:"event"`
	// Message is the human-readable audit description.
	Message string `json:"message"`
	// Payload contains event-specific JSON data and may be empty.
	Payload Payload `json:"payload,omitempty"`
	// Origin is nullable network context for the request that produced the event.
	Origin *RequestOrigin `json:"origin,omitempty"`
	// CreatedAt is the activity creation date-time.
	CreatedAt Timestamp `json:"created_at"`
}

// RequestOrigin captures the network context recorded for an activity.
type RequestOrigin struct {
	// IP is the source IP address recorded by the API.
	IP string `json:"ip"`
	// UserAgent is the source HTTP User-Agent value.
	UserAgent string `json:"user-agent"`
}

// RenameDocumentRequest is the body for PATCH /documents/{document_id}.
type RenameDocumentRequest struct {
	// Name is the required replacement display name (maximum 255 characters).
	Name string `json:"name"`
}

// CreateDocumentFromTemplateOptions is the body for
// POST /accounts/{id}/templates/{tid}/documents.
type CreateDocumentFromTemplateOptions struct {
	// Name optionally overrides the template's document name.
	Name string `json:"name,omitempty"`
	// Message is an optional signing-invitation message.
	Message string `json:"message,omitempty"`
	// EditorFields supplies optional values for template editor fields.
	EditorFields []TemplateEditorField `json:"editor_fields,omitempty"`
	// ExpiresAt is an optional ISO-8601 signing expiration date/time.
	ExpiresAt string `json:"expires_at,omitempty"`
	// Tags are tag names to attach to the new document. Unknown names are
	// auto-created; the template's default-document-tags are always applied and
	// merged with these.
	Tags []string `json:"tags,omitempty"`
	// Signers is the required role-to-signer mapping. CreateFromTemplate replaces
	// this field with its signers argument.
	Signers []TemplateSigner `json:"signers"`
}

// TemplateEditorField is a single value bound to a template editor field.
type TemplateEditorField struct {
	// FieldID is the required template field identifier.
	FieldID string `json:"field_id"`
	// Value is the required editor value. The OpenAPI declares a string; any is
	// retained for compatibility with values accepted by earlier API versions.
	Value any `json:"value"`
}

// TemplateSigner pairs a real signer with a template role.
type TemplateSigner struct {
	// RoleID is the required template role identifier.
	RoleID string `json:"role_id"`
	// ID is the existing signer identifier required for document creation; omit it for
	// the estimate-cost endpoint, whose signer shape does not include an ID.
	ID string `json:"id,omitempty"`
	// VerificationMethod is the optional API verification-method code.
	VerificationMethod string `json:"verification_method,omitempty"`
	// NotificationMethods contains optional API delivery-channel codes.
	NotificationMethods []string `json:"notification_methods,omitempty"`
	// Step controls sequential signing order (positive integer starting at 1).
	// Signers sharing a step sign in parallel; a step is activated only after
	// every signer in the previous step has signed. Optional; omit to notify all
	// signers at once. Ignored by the estimate-cost endpoint.
	Step *int `json:"step,omitempty"`
}

// UploadAndRequestSignaturesSigner is a high-level signer payload accepted by
// the Client.UploadAndRequestSignatures convenience helper.
type UploadAndRequestSignaturesSigner struct {
	// Name is the required signer full name.
	Name string
	// Email is an optional signer email address; empty omits it.
	Email string
	// WhatsAppPhoneNumber is an optional international telephone number; empty omits it.
	WhatsAppPhoneNumber string
}

// UploadAndRequestSignaturesResult is returned by Client.UploadAndRequestSignatures.
type UploadAndRequestSignaturesResult struct {
	// Document is the uploaded document response.
	Document *Document
	// Assignment is the virtual assignment response.
	Assignment *Assignment
	// SignerIDs lists newly created signer UUIDs in input order.
	SignerIDs []string
}

// VerifyDocumentResult is the response from GET /documents/{hash}/verify.
type VerifyDocumentResult struct {
	// Hash is the signature hash that was verified.
	Hash string `json:"hash"`
	// ID is the nullable matched document identifier.
	ID *string `json:"id,omitempty"`
	// Status is the nullable matched document lifecycle code.
	Status *string `json:"status,omitempty"`
	// PageCount is the nullable page count as encoded by the verification API.
	PageCount *string `json:"page_count,omitempty"`
	// SignerCount is the nullable signer count as encoded by the verification API.
	SignerCount *string `json:"signer_count,omitempty"`
	// CompletedCount is the nullable number of completed signer assignments.
	CompletedCount *int `json:"completed_count,omitempty"`
	// CompletedAt is the nullable signing-completion date-time.
	CompletedAt *Timestamp `json:"completed_at,omitempty"`
	// VerifiedAt is the date-time at which verification ran.
	VerifiedAt Timestamp `json:"verified_at"`
	// IsValid reports whether the supplied hash identifies a valid document.
	IsValid bool `json:"is_valid"`
	// Message is the API's human-readable verification result.
	Message string `json:"message"`
}

// DocumentStatusInfo describes a single status code returned by GET /documents/statuses.
type DocumentStatusInfo struct {
	// Code is the machine-readable document status value.
	Code string `json:"code"`
	// Deletable reports whether documents in this status may be deleted.
	Deletable bool `json:"deletable"`
}

// PublicDocumentInfo is the legacy reduced projection decoded by the deprecated
// PublicDocumentResource.Get method. The current endpoint returns Document.
type PublicDocumentInfo struct {
	// Resource is the API resource discriminator when present.
	Resource string `json:"resource,omitempty"`
	// ID is the public document identifier.
	ID string `json:"id"`
	// Name is the public document display name.
	Name string `json:"name"`
	// PageCount is the page count as encoded by the public API.
	PageCount string `json:"page_count"`
	// CreatedBy is the document creator label exposed publicly.
	CreatedBy string `json:"created_by"`
}

// SendDocumentTokenRequest is the body for PUT /public/documents/{id}/send-token.
type SendDocumentTokenRequest struct {
	// Email is the optional recipient email documented by the current API contract.
	Email string `json:"email,omitempty"`
	// Recipient is retained for compatibility with the legacy request shape.
	// Deprecated: use Email or PublicDocumentResource.SendTokenByEmail.
	Recipient string `json:"recipient,omitempty"`
	// Channel is retained for compatibility with the legacy request shape.
	// Deprecated: the current API contract only documents email delivery.
	Channel string `json:"channel,omitempty"`
}

// SendDocumentTokenResult is the legacy data payload decoded by the deprecated
// PublicDocumentResource.SendToken method. The current endpoint is envelope-only.
type SendDocumentTokenResult struct {
	// Document is the limited public-document payload associated with the token.
	Document PublicDocumentInfo `json:"document"`
	// Channel is the legacy delivery channel returned by the API.
	Channel string `json:"channel"`
	// Recipient is the legacy destination returned by the API.
	Recipient string `json:"recipient"`
}
